# Generated by Django 5.0.6 on 2024-07-18 09:01

import musicApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=musicApi.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
